/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculator;

/**
 *
 * @author davog
 */
public class CalcFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalcFrame
     */
    public CalcFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_1 = new javax.swing.JButton();
        B_2 = new javax.swing.JButton();
        B_3 = new javax.swing.JButton();
        B_4 = new javax.swing.JButton();
        B_5 = new javax.swing.JButton();
        B_6 = new javax.swing.JButton();
        B_7 = new javax.swing.JButton();
        B_8 = new javax.swing.JButton();
        B_9 = new javax.swing.JButton();
        B_0 = new javax.swing.JButton();
        B_Dot = new javax.swing.JButton();
        B_Negate = new javax.swing.JButton();
        B_Mul = new javax.swing.JButton();
        B_Add = new javax.swing.JButton();
        B_Sub = new javax.swing.JButton();
        B_Eql = new javax.swing.JButton();
        B_1By = new javax.swing.JButton();
        B_Sqr = new javax.swing.JButton();
        B_Sqrt = new javax.swing.JButton();
        B_Div = new javax.swing.JButton();
        B_Perc = new javax.swing.JButton();
        B_CE = new javax.swing.JButton();
        B_C = new javax.swing.JButton();
        B_Del = new javax.swing.JButton();
        Expression = new javax.swing.JTextField();
        Number = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyCalculator");
        setIconImages(null);
        setResizable(false);

        B_1.setText("1");
        B_1.setFocusPainted(false);
        B_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_1ActionPerformed(evt);
            }
        });

        B_2.setText("2");
        B_2.setFocusPainted(false);
        B_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_2ActionPerformed(evt);
            }
        });

        B_3.setText("3");
        B_3.setFocusPainted(false);
        B_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_3ActionPerformed(evt);
            }
        });

        B_4.setText("4");
        B_4.setToolTipText("");
        B_4.setFocusPainted(false);
        B_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_4ActionPerformed(evt);
            }
        });

        B_5.setText("5");
        B_5.setFocusPainted(false);
        B_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_5ActionPerformed(evt);
            }
        });

        B_6.setText("6");
        B_6.setFocusPainted(false);
        B_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_6ActionPerformed(evt);
            }
        });

        B_7.setText("7");
        B_7.setFocusPainted(false);
        B_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_7ActionPerformed(evt);
            }
        });

        B_8.setText("8");
        B_8.setFocusPainted(false);
        B_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_8ActionPerformed(evt);
            }
        });

        B_9.setText("9");
        B_9.setFocusPainted(false);
        B_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_9ActionPerformed(evt);
            }
        });

        B_0.setText("0");
        B_0.setFocusPainted(false);
        B_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_0ActionPerformed(evt);
            }
        });

        B_Dot.setText(".");
        B_Dot.setFocusPainted(false);
        B_Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DotActionPerformed(evt);
            }
        });

        B_Negate.setText("±");
        B_Negate.setFocusPainted(false);
        B_Negate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_NegateActionPerformed(evt);
            }
        });

        B_Mul.setText("x");
        B_Mul.setFocusPainted(false);
        B_Mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MulActionPerformed(evt);
            }
        });

        B_Add.setText("+");
        B_Add.setFocusPainted(false);
        B_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AddActionPerformed(evt);
            }
        });

        B_Sub.setText("-");
        B_Sub.setFocusPainted(false);
        B_Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SubActionPerformed(evt);
            }
        });

        B_Eql.setText("=");
        B_Eql.setFocusPainted(false);
        B_Eql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EqlActionPerformed(evt);
            }
        });

        B_1By.setText("⅟x");
        B_1By.setFocusPainted(false);
        B_1By.setInheritsPopupMenu(true);
        B_1By.setName(""); // NOI18N
        B_1By.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_1ByActionPerformed(evt);
            }
        });

        B_Sqr.setText("x²");
        B_Sqr.setFocusPainted(false);
        B_Sqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SqrActionPerformed(evt);
            }
        });

        B_Sqrt.setText("√x");
        B_Sqrt.setFocusPainted(false);
        B_Sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SqrtActionPerformed(evt);
            }
        });

        B_Div.setText("÷");
        B_Div.setFocusPainted(false);
        B_Div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DivActionPerformed(evt);
            }
        });

        B_Perc.setText("%");
        B_Perc.setFocusPainted(false);
        B_Perc.setInheritsPopupMenu(true);
        B_Perc.setName(""); // NOI18N
        B_Perc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PercActionPerformed(evt);
            }
        });

        B_CE.setText("CE");
        B_CE.setFocusPainted(false);
        B_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CEActionPerformed(evt);
            }
        });

        B_C.setText("C");
        B_C.setFocusPainted(false);
        B_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CActionPerformed(evt);
            }
        });

        B_Del.setText("⌫");
        B_Del.setFocusPainted(false);
        B_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DelActionPerformed(evt);
            }
        });

        Expression.setEditable(false);
        Expression.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Expression.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Expression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpressionActionPerformed(evt);
            }
        });

        Number.setEditable(false);
        Number.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Number.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Number.setText("0");
        Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Expression)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B_Perc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_C, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_Del, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B_1By, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_Sqr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_Sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_Div, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(B_Negate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B_0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(B_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(B_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B_Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_Mul, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_Eql, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Number))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Expression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_Del, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B_Perc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_C, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_Div, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B_1By, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_Sqr, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_Sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_Mul, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_Eql, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_Negate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    private boolean delUsed = false;
    
    private void B_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_1ActionPerformed
        if("Undefined".equals(Number.getText()))
        Number.setText("1"); 
        else{
        if(("0".equals(Number.getText())))
            Number.setText("1");
        else
            Number.setText(Number.getText() + "1"); 
        }
    }//GEN-LAST:event_B_1ActionPerformed

    private void B_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_2ActionPerformed
        if("Undefined".equals(Number.getText()))
        Number.setText("2");    
        else{
        if(("0".equals(Number.getText())))
            Number.setText("2");
        else
            Number.setText(Number.getText() + "2"); 
        }
    }//GEN-LAST:event_B_2ActionPerformed

    private void B_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_3ActionPerformed
        if("Undefined".equals(Number.getText()))
        Number.setText("3");    
        else{
        if(("0".equals(Number.getText())))
            Number.setText("3");
        else
            Number.setText(Number.getText() + "3"); 
        }
    }//GEN-LAST:event_B_3ActionPerformed

    private void B_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_4ActionPerformed
        if("Undefined".equals(Number.getText()))
        Number.setText("4");    
        else{
        if(("0".equals(Number.getText())))
            Number.setText("4");
        else
            Number.setText(Number.getText() + "4"); 
        }
    }//GEN-LAST:event_B_4ActionPerformed

    private void B_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_5ActionPerformed
        if("Undefined".equals(Number.getText()))
        Number.setText("5");    
        else{
        if(("0".equals(Number.getText())))
            Number.setText("5");
        else
            Number.setText(Number.getText() + "5"); 
        }
    }//GEN-LAST:event_B_5ActionPerformed

    private void B_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_6ActionPerformed
        if("Undefined".equals(Number.getText()))
        Number.setText("6");    
        else{
        if(("0".equals(Number.getText())))
            Number.setText("6");
        else
            Number.setText(Number.getText() + "6"); 
        }
    }//GEN-LAST:event_B_6ActionPerformed

    private void B_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_7ActionPerformed
        if("Undefined".equals(Number.getText()))
        Number.setText("7");    
        else{
        if(("0".equals(Number.getText())))
            Number.setText("7");
        else
            Number.setText(Number.getText() + "7"); 
        }
    }//GEN-LAST:event_B_7ActionPerformed

    private void B_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_8ActionPerformed
        if("Undefined".equals(Number.getText()))
        Number.setText("8");    
        else{
        if(("0".equals(Number.getText())))
            Number.setText("8");
        else
            Number.setText(Number.getText() + "8"); 
        }
    }//GEN-LAST:event_B_8ActionPerformed

    private void B_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_9ActionPerformed
        if("Undefined".equals(Number.getText()))
        Number.setText("9");    
        else{ 
        if(("0".equals(Number.getText())))
            Number.setText("9");
        else
            Number.setText(Number.getText() + "9");
        }
    }//GEN-LAST:event_B_9ActionPerformed

    private void B_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_0ActionPerformed
        if("Undefined".equals(Number.getText()))
        Number.setText("0");    
        else{
        if(!("0".equals(Number.getText())))
        Number.setText(Number.getText() + "0"); }
    }//GEN-LAST:event_B_0ActionPerformed

    private void B_DotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DotActionPerformed
        if(!delUsed)
        {
            Number.setText(Number.getText() + "."); 
            delUsed = true;
        }
    }//GEN-LAST:event_B_DotActionPerformed

    private void B_NegateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_NegateActionPerformed
        String num = Number.getText();
        if(!"0".equals(num))
        {
            if(num.charAt(0) == '-')
                Number.setText(num.substring(1));
            else Number.setText("-" + num);
        }
    }//GEN-LAST:event_B_NegateActionPerformed

    private void B_MulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MulActionPerformed
        Operation("*");
    }//GEN-LAST:event_B_MulActionPerformed

    private void B_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AddActionPerformed
        Operation("+");
    }//GEN-LAST:event_B_AddActionPerformed

    private void B_SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SubActionPerformed
        Operation("-");
    }//GEN-LAST:event_B_SubActionPerformed

    private void B_EqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EqlActionPerformed
        Operation("=");
    }//GEN-LAST:event_B_EqlActionPerformed

    private void B_1ByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_1ByActionPerformed
        try
            {
            float num = Float.parseFloat(Number.getText());
            if(num == 0)
            {
                Expression.setText("");
                Number.setText("Undefined");
            }
            else 
            {
                num = 1 / num;
                if(num==Math.ceil(num))
                    Number.setText(String.valueOf(Math.round(num)));
                else
                {
                    Number.setText(String.valueOf(num));
                    delUsed = true;
                }
            } 
        }
        catch(NumberFormatException e){
        }
    }//GEN-LAST:event_B_1ByActionPerformed

    private void B_SqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SqrActionPerformed
        try
        {
            float num = Float.parseFloat(Number.getText());
            num = num * num;
            if(num==Math.ceil(num))
                Number.setText(String.valueOf(Math.round(num)));
            else
            {
                Number.setText(String.valueOf(num));
                delUsed = true;
            }
        }
        catch(NumberFormatException e){
        }
    }//GEN-LAST:event_B_SqrActionPerformed

    private void B_SqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SqrtActionPerformed
        try
        {
            float num = Float.parseFloat(Number.getText());
            if(num<0){
                Number.setText("Undefined");
                Expression.setText("");
            }
            else
            {
                num = (float) Math.sqrt(num);
                if(num==Math.ceil(num))
                    Number.setText(String.valueOf(Math.round(num)));

                else
                {
                    Number.setText(String.valueOf(num));
                    delUsed = true;
                }
            }
        }
        catch(NumberFormatException e){
        }
    }//GEN-LAST:event_B_SqrtActionPerformed

    private void B_DivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DivActionPerformed
        
        Operation("/");
    }//GEN-LAST:event_B_DivActionPerformed
    
    private void Operation(String operation){
        float ans = 0;
        if("Undefined".equals(Number.getText()))
        Number.setText("0");    
        
        if("".equals(Expression.getText()))
        {
            Expression.setText(Number.getText() + operation);
            Number.setText("0");
        }
        else{
            String expression = Expression.getText();
            String Calcoperation = expression.substring(expression.length()-1);
            float num;
            
            if(!"=".equals(Calcoperation))
                num = Float.parseFloat(expression.substring(0, expression.length()-1));
            else
                num = Float.parseFloat(Number.getText());
                
            if(null != Calcoperation) 
            switch (Calcoperation) {
                case "/":
                    ans = num / Float.parseFloat(Number.getText());
                    break;
                case "*":
                    ans = num * Float.parseFloat(Number.getText());
                    break;
                case "+":
                    ans = num + Float.parseFloat(Number.getText());
                    break;
                case "-":
                    ans = num - Float.parseFloat(Number.getText());
                    break;
                case "%":
                    ans = num * (Float.parseFloat(Number.getText())/100);
                    break;
                default:
                    break;
            }
            
            if("/".equals(Calcoperation) &&  Float.parseFloat(Number.getText()) == 0)
            { 
                Number.setText("Undefined");
                Expression.setText("");
            }
            else if(!"=".equals(operation) && !"=".equals(Calcoperation))
            {
                Expression.setText((ans) + operation);
                Number.setText("0");
            }
            else if("=".equals(Calcoperation)){
                Expression.setText(Number.getText() + operation);
                //Number.setText("0");
            }
            else if("=".equals(operation))
            {
                Expression.setText(Expression.getText() + Number.getText() + operation);
                if(ans==Math.ceil(ans))
                     Number.setText(String.valueOf(Math.round(ans)));
                else
                {
                    Number.setText(String.valueOf(ans));
                    delUsed = true;
                }
            }

        }
    }
    
    private void B_PercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PercActionPerformed
        Operation("%");
    }//GEN-LAST:event_B_PercActionPerformed

    private void B_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CEActionPerformed
        Number.setText("0");
        delUsed = false;
    }//GEN-LAST:event_B_CEActionPerformed

    private void B_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CActionPerformed
        Number.setText("0");
        Expression.setText("");
        delUsed = false;
    }//GEN-LAST:event_B_CActionPerformed

    private void B_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DelActionPerformed
        String num = Number.getText();
        
        if(num.charAt(num.length()-1) == '.')
            delUsed = false;
        
        num = num.substring(0, num.length()-1);

        if("".equals(num))
            num = "0";
        Number.setText(num);
    }//GEN-LAST:event_B_DelActionPerformed

    private void ExpressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpressionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpressionActionPerformed

    private void NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_0;
    private javax.swing.JButton B_1;
    private javax.swing.JButton B_1By;
    private javax.swing.JButton B_2;
    private javax.swing.JButton B_3;
    private javax.swing.JButton B_4;
    private javax.swing.JButton B_5;
    private javax.swing.JButton B_6;
    private javax.swing.JButton B_7;
    private javax.swing.JButton B_8;
    private javax.swing.JButton B_9;
    private javax.swing.JButton B_Add;
    private javax.swing.JButton B_C;
    private javax.swing.JButton B_CE;
    private javax.swing.JButton B_Del;
    private javax.swing.JButton B_Div;
    private javax.swing.JButton B_Dot;
    private javax.swing.JButton B_Eql;
    private javax.swing.JButton B_Mul;
    private javax.swing.JButton B_Negate;
    private javax.swing.JButton B_Perc;
    private javax.swing.JButton B_Sqr;
    private javax.swing.JButton B_Sqrt;
    private javax.swing.JButton B_Sub;
    private javax.swing.JTextField Expression;
    private javax.swing.JTextField Number;
    // End of variables declaration//GEN-END:variables
}
